import random
import json
import time
from common import CommonDatabase


def generate_random_number():
    number = ''.join([str(random.randint(0, 9)) for _ in range(10)])
    return "test" + number


def rk_body(ordertype, orderline, wh_id, creatorname, creator, producttype, pruduct_name, supplier_name):
    data_result = CommonDatabase().select_data("*", "base_tm_sku", f"sku_name = '{pruduct_name}'")
    data_category = CommonDatabase().select_data("*", "base_tm_sku_category",
                                                 f"id = {data_result['sku_category_id']}")
    gsp_data = CommonDatabase().select_data("*", "base_tm_sku_gsp", f"sku_id = {data_result['id']}")
    gsp_date_data = CommonDatabase().select_data("*", "base_tm_sku_certificate",
                                                 f"sku_id = {data_result['id']}")
    supplier_data = CommonDatabase().select_data("*", "base_tm_supplier", f" supplier_name= '{supplier_name}'")
    rk_data = {
        "jobType": "PTDD",
        "orderSource": "WMS",
        "ownerName": "智汇奇策科技有限公司",
        "supplierName": f"{supplier_name}--智汇奇策科技有限公司",  # 供应商名称
        "orderStatus": "CJ",
        "origSys": "WMS",
        "partnerType": "SUPPLIER",
        "origNo": f"{generate_random_number()}",
        "orderType": f"{ordertype}",
        "ownerId": "1770570116141568",
        "supplierId": f"{supplier_data['id']}",
        "productFormType": f"{producttype}",
        "dtReqList": [
            {
                "sourceProductionDateType": "0",
                "sourceInvalidDateType": "0",
                "skuId": f"{data_result['id']}",  # 商品sku_id
                "key": f"{data_result['id']}",  # 商品key
                "companyCode": f"{data_result['company_code']}",  # 公司编码
                "whId": wh_id,  # 仓库id
                "id": f"{data_result['id']}",
                "remark": "",
                "createTime": str(f'{time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())}'),
                "creator": f"{creator}",  # 创建人id
                "creatorName": f"{creatorname}",
                "updateTime": f'{time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())}',
                "updater": f"{creator}",
                "updaterName": f"{creatorname}",
                "createTimeStr": f'{time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())}',
                "updateTimeStr": f'{time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())}',
                "ownerId": data_result['owner_id'],
                "sysSkuCode": f"{data_result['sys_sku_code']}",
                "skuCode": f"{data_result['sku_code']}",
                "skuName": f"{data_result['sku_name']}",
                "origSys": "WMS",
                "spec": f"{data_result['spec']}",
                "ephedrine": data_result['ephedrine'],
                "tradeName": f"{data_result['trade_name']}",
                "skuCategoryId": data_result['sku_category_id'],
                "brandName": "",
                "barcode": f"{data_result['barcode']}",
                "mainUnit": f"{data_result['main_unit']}",
                "length": str(data_result['length']),
                "width": str(data_result['width']),
                "height": str(data_result['height']),
                "vol": str(data_result['vol']),
                "grossWeight": str(data_result['gross_weight']),
                "netWeight": str(data_result['net_weight']),
                "abc": f"{data_result['abc']}",
                "zjAbc": f"{data_result['zj_abc']}",
                "mfgId": data_result['mfg_id'],
                "mfg": f"{data_result['mfg']}",
                "outFactoryCode": "",
                "model": "",
                "originCountry": f"{data_result['origin_country']}",
                "logistics": "",
                "isBatchManage": data_result['is_batch_manage'],
                "isValidity": data_result['is_validity'],
                "validityType": "",
                "validityDay": data_result['validity_day'],
                "warmValidityDay": data_result['warm_validity_day'],
                "isValuables": 0,
                "isCombination": 0,
                "isGift": 0,
                "isConsumables": 0,
                "isChangeable": 0,
                "isProneToMistakes": 0,
                "isHeteromorphicProduct": 0,
                "perQty": data_result['per_qty'],
                "midPackQty": data_result['mid_pack_qty'],
                "isEnable": data_result['is_enable'],
                "auditOpinion": None,
                "auditStatus": None,
                "auditTime": None,
                "auditName": None,
                "barcodeTwo": "",
                "barcodeThree": "",
                "taxCode": "",
                "taxName": "",
                "taxFee": None,
                "tempControl": "CW",
                "scatteredProperties": "",
                "gmpCertNo": "",
                "approvalNumber": f"{data_result['approval_number']}",
                "categoryPrincipal": "",
                "permitHolder": "",
                "qtyStandard": "",
                "mnemonicCode": f"{data_result['mnemonic_code']}",
                "limitSaleDay": data_result['limit_sale_day'],
                "routeOfAdministration": "",
                "tempMax": None,
                "tempMin": None,
                "minInvoicingUnit": None,
                "optimistic": 0,
                "packFactoryId": 0,
                "productFormType": f"{data_result['product_form_type']}",
                "isLimitMidPack": 0,
                "hasAnaleptic": 0,
                "tempCondition": None,
                "diCode": None,
                "erpUpdaterName": None,
                "erpUpdateTime": None,
                "erpCreatorName": None,
                "erpCreateTime": None,
                "creditType": None,
                "medicalInsuranceCode": None,
                "instrumentModel": None,
                "entrustMfgId": None,
                "hasAnalepticName": "否",
                "ephedrineName": "是",
                "isDoubleCheckName": "否",
                "isDoubleCheck": 0,
                "isFirstCamp": 0,
                "isFirstCampName": "否",
                "isLimitMidPackName": "否",
                "prodLicenseCode": None,
                "ownerCode": "ZHQCHZ",
                "ownerName": "智汇奇策科技有限公司",
                "skuCategoryName": f"{data_category['category_name']}",
                "skuCategoryCode": None,
                "skuCategoryParentId": None,
                "productFormTypeName": f"{data_category['category_name']}",
                "maintenanceType": f"{gsp_data['maintenance_type']}",
                "maintenanceTypeName": "一般养护",
                "skuCategorySecondId": None,
                "drugForm": "_",
                "drugFormSpec": "",
                "grmpCertificateNo": None,
                "grmpExpirationDate": f"{gsp_date_data['expiration_date']}",
                "pzwhExpirationDate": None,
                "bomVOList": None,
                "consumablesVOList": None,
                "certificateVOList": None,
                "approvalNumberList": None,
                "gspData": None,
                "imageVOList": None,
                "packingVOList": None,
                "tempControlName": "常温",
                "isEnableName": "是",
                "scatteredPropertiesName": None,
                "packFactoryName": "",
                "entrustMfgName": "",
                "isValidityName": "否",
                "sumUsableQty": None,
                "auditStatusName": None,
                "isDrugSuperCode": 0,
                "isDrugSuperCodeName": "否",
                "auditorTime": None,
                "orgId": "1770560509055488",
                "orgName": "零售事业部",
                "orgFullName": "智汇奇策科技有限公司_零售事业部",
                "supplierId": f"{supplier_data['id']}",
                "supplierName": f"{supplier_name}--智汇奇策科技有限公司",
                "inOrderQty": f"{orderline}",
                "amount": "1123",
                "unitPrice": "1.111",
                "manageValidDay": "30",
                "_X_ROW_KEY": "row_61"
            }
        ],
        "extendReq": {
            "refundReason": None,
            "isSqueezed": 1
        }
    }

    return json.dumps(rk_data)
    # return rk_data


def select_data(key):
    data = {"orderNo": f"{key}"}
    return json.dumps(data)


def asn_data(order_num, producttype, pruduct_name, supplier_name):
    data_result = CommonDatabase().select_data("*", "base_tm_sku", f"sku_name = '{pruduct_name}'")
    data_category = CommonDatabase().select_data("*", "base_tm_sku_category",
                                                 f"id = {data_result['sku_category_id']}")
    data = {
        "_X_ROW_KEY": "row_236",
        "dtList": [
            {
                "key": "None",
                "companyCode": None,
                "whId": None,
                "id": None,
                "remark": None,
                "createTime": None,
                "creator": None,
                "creatorName": None,
                "updateTime": None,
                "updater": None,
                "updaterName": None,
                "createTimeStr": None,
                "updateTimeStr": None,
                "inOrderId": 1829964491837952,
                "orgId": None,
                "orgName": "零售事业部",
                "orgFullName": None,
                "skuId": f"{data_result['id']}",
                "skuCode": f"{data_result['sku_code']}",
                "commodityQty": order_num,
                "recQty": 0,
                "unitPrice": 1,
                "amount": 100,
                "origRowNo": None,
                "supplierId": None,
                "supplierName": f"{supplier_name}--智汇奇策科技有限公司",
                "batchNo": None,
                "sourceProductionBatch": None,
                "sourceProductionDate": None,
                "sourceInvalidDate": None,
                "centralizedPurchaseAssignQty": 0,
                "ratio": None,
                "rejectQty": 0,
                "originalOutOrderErpNo": None,
                "optimistic": None,
                "priceIncludingTax": None,
                "taxRatio": None,
                "amountExcludingTax": None,
                "taxAmount": None,
                "amountTotal": None,
                "backQty": None,
                "buyer": None,
                "manageValidDay": None,
                "commonSku": {
                    "skuId": data_result['id'],
                    "skuCode": f"{data_result['sku_code']}",
                    "barcode": f"{data_result['barcode']}",
                    "skuName": f"{data_result['sku_name']}",
                    "skuCategoryId": data_result['sku_category_id'],
                    "skuCategoryName": f"{data_category['category_name']}",
                    "skuCategoryCode": None,
                    "skuBigCategoryCode": None,
                    "skuBigCategoryName": None,
                    "spec": f"{data_result['spec']}",
                    "mainUnit": f"{data_result['main_unit']}",
                    "perQty": data_result['per_qty'],
                    "originCountry": f"{data_result['origin_country']}",
                    "drugForm": "_",
                    "tradeName": f"{data_result['trade_name']}",
                    "approvalNumber": f"{data_result['approval_number']}",
                    "brandName": "",
                    "mfgName": f"{data_result['mfg']}",
                    "mfg": None,
                    "permitHolder": "",
                    "tempControl": "CW",
                    "validityDay": None,
                    "tempControlName": "常温",
                    "tempMax": None,
                    "tempMin": None,
                    "mnemonicCode": f"{data_result['mnemonic_code']}",
                    "instrumentModel": None
                },
                "inOrderDtId": None,
                "inOrderDtIdList": "1829964491887106",
                "ownerId": None,
                "ownerName": "智汇奇策科技有限公司",
                "planQty": order_num,
                "waitRecQty": order_num,
                "extractedQty": 0,
                "extractableQty": order_num,
                "alreadyRecQty": None,
                "actualRecQty": None,
                "shouldRecVarietiesQty": None,
                "alreadyRecVarietiesQty": None,
                "inOrderNo": "R20240716000005",
                "erpOrderNo": "test5749500583",
                "origPurchaseOrderNo": None,
                "productFormType": f"{producttype}",
                "productFormTypeName": f"{data_category['category_name']}",
                "categoryName": f"{data_category['category_name']}",
                "subPackagingEnterprise": None,
                "seq": None,
                "productionBatch": None,
                "productionDate": None,
                "productionDateYm": None,
                "invalidDate": None,
                "invalidDateYm": None,
                "wholePieceQty": None,
                "scatteredQty": None,
                "length": 15,
                "width": 15,
                "height": 15,
                "bigWeight": None,
                "bigVolume": None,
                "bigPackQty": 1000,
                "middlePackQty": None,
                "volume": None,
                "weight": None,
                "originalBatchNo": None,
                "productionBatchDisabled": False,
                "productionDateDisabled": False,
                "productionDateYmDisabled": False,
                "invalidDateDisabled": False,
                "invalidDateYmDisabled": False,
                "cooperativePartnerName": f"{supplier_name}--智汇奇策科技有限公司",
                "_X_ROW_KEY": "row_313"
            }
        ]
    }
    return json.dumps(data)


def ys_data(asnid, asnno, inorder, erpno, ordertype, asndtid, commodityQty, xrowkey, creatorname, creator, pruduct_name,
            supplier_name):
    data_result = CommonDatabase().select_data("*", "base_tm_sku", f"sku_name = '{pruduct_name}'")
    data_category = CommonDatabase().select_data("*", "base_tm_sku_category",
                                                 f"id = {data_result['sku_category_id']}")
    supplier_data = CommonDatabase().select_data("*", "base_tm_supplier", f" supplier_name= '{supplier_name}'")
    product_batch = time.strftime('%Y-%m-%d').replace('-', '') + "001"
    data = {
        "code": 0,
        "msg": None,
        "asnId": asnid,
        "qcId": None,
        "asnNo": f"{asnno}",
        "productFormType": f"{data_result['product_form_type']}",
        "wmsBusinessType": "TO_B",
        "ownerId": 1770570116141568,
        "ownerName": "智汇奇策科技有限公司",
        "orgName": "零售事业部",
        "inOrderNo": f"{inorder}",
        "erpOrderNo": f"{erpno}",
        "origPurchaseOrderNo": None,
        "supplierId": f"{supplier_data['id']}",
        "supplierName": f"{supplier_name}--智汇奇策科技有限公司",
        "customerName": None,
        "storeName": None,
        "orderSource": "WMS",
        "asnType": f"{ordertype}",
        "asnStatus": "CJ",
        "buyer": "",
        "arriveType": "TYGSSH",
        "shipTool": "XSHC",
        "carrierName": None,
        "cooperativePartnerName": f"{data_result['product_form_type']}",
        "refundReason": None,
        "shipAddress": None,
        "originalOutOrderErpNo": None,
        "creator": f"{creator}",
        "creatorName": f"{creatorname}",
        "shipTime": "2024-07-16 00:00",
        "arriveTime": "2024-07-16 00:00",
        "createTime": "2024-07-16 17:37:57",
        "print": False,
        "ejectConfirmationBox": False,
        "coldChainFlag": False,
        "waitRecList": [
            {
                "commonSku": {
                    "skuId": f"{data_result['id']}",
                    "skuCode": f"{data_result['sku_code']}",
                    "barcode": f"{data_result['barcode']}",
                    "skuName": f"{data_result['sku_name']}",
                    "skuCategoryId": data_result['sku_category_id'],
                    "skuCategoryName": f"{data_category['category_name']}",
                    "skuCategoryCode": None,
                    "skuBigCategoryCode": None,
                    "skuBigCategoryName": None,
                    "spec": f"{data_result['spec']}",
                    "mainUnit": f"{data_result['main_unit']}",
                    "perQty": data_result['per_qty'],
                    "originCountry": f"{data_result['origin_country']}",
                    "drugForm": "_",
                    "tradeName": f"{data_result['trade_name']}",
                    "approvalNumber": f"{data_result['approval_number']}",
                    "brandName": "",
                    "mfgName": f"{data_result['mfg']}",
                    "mfg": None,
                    "permitHolder": "",
                    "tempControl": "CW",
                    "validityDay": None,
                    "tempControlName": "常温",
                    "tempMax": None,
                    "tempMin": None,
                    "mnemonicCode": f"{data_result['mnemonic_code']}",
                    "instrumentModel": None
                },
                "asnDtId": asndtid,
                "skuId": f"{data_result['id']}",
                "skuCode": f"{data_result['sku_code']}",
                "commodityQty": commodityQty,
                "alreadyRecQty": 0,
                "waitRecQty": commodityQty,
                "recQty": commodityQty,
                "wholePieceQty": 0,
                "scatteredQty": commodityQty,
                "unitPrice": 1,
                "amount": commodityQty,
                "length": str(data_result['length']),
                "width": str(data_result['width']),
                "height": str(data_result['height']),
                "bigWeight": 2.5,
                "bigVolume": 3375,
                "bigPackQty": 1000,
                "middlePackQty": 25,
                "volume": 3.375,
                "weight": 0.0025,
                "isDrugSuperCode": 0,
                "productionBatch": f"{product_batch}",
                "productionDate": None,
                "productionDateYm": "2024-01",
                "invalidDate": None,
                "invalidDateYm": "2024-12",
                "instoreDate": None,
                "skuMiddleCategoryName": None,
                "tempControl": "CW",
                "seq": "1",
                "productionBatchDisabled": False,
                "productionDateDisabled": False,
                "productionDateYmDisabled": False,
                "invalidDateDisabled": False,
                "invalidDateYmDisabled": False,
                "isChecked": True,
                "isCheckedNo": True,
                "isSecondCheck": "allFinish",
                "productFormType": "YP",
                "_X_ROW_KEY": "row_193",
                "tick": "ok",
                "notick": "ok"
            }
        ],
        "alreadyRecList": True,
        "alreadyRecNearEffectivePeriodList": True,
        "asnStatusName": "创建",
        "asnTypeName": "采购订单",
        "wmsBusinessTypeName": "ToB",
        "orderSourceName": "WMS",
        "productFormTypeName": f"{data_category['category_name']}",
        "dtList": [
            {
                "commonSku": {
                    "skuId": f"{data_result['id']}",
                    "skuCode": f"{data_result['sku_code']}",
                    "barcode": f"{data_result['barcode']}",
                    "skuName": f"{data_result['sku_name']}",
                    "skuCategoryId": data_result['sku_category_id'],
                    "skuCategoryName": f"{data_category['category_name']}",
                    "skuCategoryCode": None,
                    "skuBigCategoryCode": None,
                    "skuBigCategoryName": None,
                    "spec": f"{data_result['spec']}",
                    "mainUnit": f"{data_result['main_unit']}",
                    "perQty": data_result['per_qty'],
                    "originCountry": f"{data_result['origin_country']}",
                    "drugForm": "_",
                    "tradeName": f"{data_result['trade_name']}",
                    "approvalNumber": f"{data_result['approval_number']}",
                    "brandName": "",
                    "mfgName": f"{data_result['mfg']}",
                    "mfg": None,
                    "permitHolder": "",
                    "tempControl": "CW",
                    "validityDay": None,
                    "tempControlName": "常温",
                    "tempMax": None,
                    "tempMin": None,
                    "mnemonicCode": f"{data_result['mnemonic_code']}",
                    "instrumentModel": None
                },
                "asnDtId": asndtid,
                "skuId": f"{data_result['id']}",
                "skuCode": f"{data_result['sku_code']}",
                "commodityQty": commodityQty,
                "alreadyRecQty": 0,
                "waitRecQty": commodityQty,
                "recQty": commodityQty,
                "wholePieceQty": 0,
                "scatteredQty": commodityQty,
                "unitPrice": 1,
                "amount": commodityQty,
                "length": str(data_result['length']),
                "width": str(data_result['width']),
                "height": str(data_result['height']),
                "bigWeight": 2.5,
                "bigVolume": 3375,
                "bigPackQty": 1000,
                "middlePackQty": 25,
                "volume": 3.375,
                "weight": 0.0025,
                "isDrugSuperCode": 0,
                "productionBatch": f"{product_batch}",
                "productionDate": None,
                "productionDateYm": "2024-01",
                "invalidDate": None,
                "invalidDateYm": "2024-12",
                "instoreDate": None,
                "skuMiddleCategoryName": None,
                "tempControl": "CW",
                "seq": "1",
                "productionBatchDisabled": False,
                "productionDateDisabled": False,
                "productionDateYmDisabled": False,
                "invalidDateDisabled": False,
                "invalidDateYmDisabled": False,
                "isChecked": True,
                "isCheckedNo": True,
                "isSecondCheck": "allFinish",
                "productFormType": f"{data_result['product_form_type']}",
                "_X_ROW_KEY": f"{xrowkey}",
                "tick": "ok",
                "notick": "ok"
            }
        ]
    }
    return data


def sj(qcid, qcNo, num, batchNo, asnNo, row, productionBatch, qcdtid, pruduct_name):
    data_result = CommonDatabase().select_data("*", "base_tm_sku", f"sku_name = '{pruduct_name}'")
    data_category = CommonDatabase().select_data("*", "base_tm_sku_category",
                                                 f"id = {data_result['sku_category_id']}")
    data = {
        "dtList": [
            {
                "key": "None",
                "companyCode": None,
                "whId": None,
                "id": None,
                "remark": None,
                "createTime": None,
                "creator": None,
                "creatorName": None,
                "updateTime": None,
                "updater": None,
                "updaterName": None,
                "createTimeStr": None,
                "updateTimeStr": None,
                "qcId": qcid,
                "qcNo": f"{qcNo}",
                "skuId": f"{data_result['id']}",
                "skuCode": f"{data_result['sku_code']}",
                "recQty": num,
                "qcQty": num,
                "oneQcQty": None,
                "batchNo": f"{batchNo}",
                "recLotId": None,
                "containerNo": "XNRQ",
                "serialNumber": None,
                "printCount": None,
                "sampleQty": num,
                "sampleWholePieceQty": 0,
                "splitInitQcDtId": None,
                "optimistic": None,
                "commonSku": {
                    "skuId": f"{data_result['id']}",
                    "skuCode": f"{data_result['sku_code']}",
                    "barcode": f"{data_result['barcode']}",
                    "skuName": f"{data_result['sku_name']}",
                    "skuCategoryId": data_result['sku_category_id'],
                    "skuCategoryName": f"{data_category['category_name']}",
                    "skuCategoryCode": None,
                    "skuBigCategoryCode": None,
                    "skuBigCategoryName": None,
                    "spec": f"{data_result['spec']}",
                    "mainUnit": f"{data_result['main_unit']}",
                    "perQty": data_result['per_qty'],
                    "originCountry": f"{data_result['origin_country']}",
                    "drugForm": "_",
                    "tradeName": f"{data_result['trade_name']}",
                    "approvalNumber": f"{data_result['approval_number']}",
                    "brandName": "",
                    "mfgName": f"{data_result['mfg']}",
                    "mfg": None,
                    "permitHolder": "",
                    "tempControl": "CW",
                    "validityDay": None,
                    "tempControlName": "常温",
                    "tempMax": None,
                    "tempMin": None,
                    "mnemonicCode": f"{data_result['mnemonic_code']}",
                    "instrumentModel": None
                },
                "commonInvBatch": {
                    "batchNo": f"{batchNo}",
                    "productionBatch": productionBatch,
                    "productionDate": "2024-01",
                    "instoreDate": "2024-07-18",
                    "invalidDate": "2024-12",
                    "sterileInvaliDate": "",
                    "sterileNo": "",
                    "asnNo": f"{asnNo}",
                    "batchAsnNo": None,
                    "po": None,
                    "perQty": data_result['per_qty'],
                    "unitPrice": 1,
                    "spellBoxSign": "",
                    "volume": None,
                    "weight": None,
                    "packQty": None
                },
                "qcDtId": qcdtid,
                "alreadyQcQty": 0,
                "waitQcQty": num,
                "wholePieceQty": 0,
                "scatteredQty": num,
                "checkResult": "HG",
                "isDoubleCheck": 0,
                "lotCode": None,
                "lotName": "虚拟验收位",
                "zoneCode": "XNKQ",
                "perQty": data_result['per_qty'],
                "spellBoxSign": "",
                "seq": "1",
                "ownerName": None,
                "orgName": None,
                "skuMiddleCategoryName": None,
                "isDoubleCheckName": "否",
                "productFormType": "YP",
                "waitScatteredQty": None,
                "waitWholePieceQty": None,
                "instrumentModel": None,
                "sampleWholePieceQtyTemp": 0,
                "sampleQtyTemp": 1,
                "sourceContainerNo": None,
                "checkedFlagApproval": True,
                "checkedFlag": True,
                "_X_ROW_KEY": f"{row}",
                "checkResultDesc": None,
                "handleMeasure": None
            }
        ],
        "qcId": qcid,
        "mac": "B0-7B-25-29-F7-04"
    }
    return data


def so_data(order_type, orderNo, num, bussinessType, out_sku):
    data_result = CommonDatabase().select_data("*", "base_tm_sku", f"sku_name = '{out_sku}'")
    data_category = CommonDatabase().select_data("*", "base_tm_sku_category",
                                                 f"id = {data_result['sku_category_id']}")
    gsp_data = CommonDatabase().select_data("*", "base_tm_sku_gsp", f"sku_id = {data_result['id']}")
    gsp_date_data = CommonDatabase().select_data("*", "base_tm_sku_certificate",
                                                 f"sku_id = {data_result['id']}")
    data = {
        "jobType": "PTDD",
        "origSys": "WMS",
        "orderStatus": "NEW_CREATE",
        "country": "CHN",
        "ownerName": "智汇奇策科技有限公司",
        "orgId": "1770560509055488",
        "orgName": "零售事业部",
        "provinceCode": "370000",
        "provinceName": "山东省",
        "cityId": "135",
        "cityCode": "370200",
        "cityName": "青岛市",
        "areaId": "1226",
        "areaCode": "370203",
        "areaName": "市北区",
        "origSysName": "WMS",
        "productFormType": "YP",
        "isPrescription": None,
        "wmsBusinessType": f"{bussinessType}",
        "origNo": f"test-erp-{int(time.time())}",
        "ownerId": "1770570116141568",
        "orderType": f"{order_type}",
        "partnerType": "SUPPLIER",
        "partnerCode": "QDHYS",
        "partnerName": "青岛医药科技集团有限公司",
        "partnerId": "1838234556355072",
        "partnerAddr": "",
        "partnerMnemonicCode": "qd",
        "erpCarrierId": "1843793990619648",
        "erpCarrierName": "新接口测试ERP承运商一号",
        "deliveryMethod": "TY",
        "provinceId": "15",
        "orderPrice": 1,
        "discountPrice": 1,
        "contactName": "测试人员",
        "contactTel": "18660282391",
        "extendReq": {
            "orderPrice": 1,
            "discountPrice": 1
        },
        "dtList": [
            {
                "productionDateType": "1",
                "invalidDateType": "1",
                "skuId": f"{data_result['id']}",
                "key": f"{data_result['id']}",
                "companyCode": f"{data_result['company_code']}",
                "whId": 1,
                "id": f"{data_result['id']}",
                "remark": "",
                "createTime": f"{data_result['create_time']}",
                "creator": f"{data_result['creator']}",
                "creatorName": f"{data_result['creator_name']}",
                "updateTime": f"{data_result['update_time']}",
                "updater": f"{data_result['updater']}",
                "updaterName": f"{data_result['updater_name']}",
                "createTimeStr": "2024-07-13 13:57:06",
                "updateTimeStr": "2024-07-15 10:38:46",
                "ownerId": data_result['owner_id'],
                "sysSkuCode": f"{data_result['sys_sku_code']}",
                "skuCode": f"{data_result['sku_code']}",
                "skuName": f"{data_result['sku_name']}",
                "origSys": f"{data_result['orig_sys']}",
                "spec": f"{data_result['spec']}",
                "ephedrine": data_result['ephedrine'],
                "tradeName": f"{data_result['trade_name']}",
                "skuCategoryId": data_result['sku_category_id'],
                "brandName": "",
                "barcode": f"{data_result['barcode']}",
                "mainUnit": f"{data_result['main_unit']}",
                "length": str(data_result['length']),
                "width": str(data_result['width']),
                "height": str(data_result['height']),
                "vol": str(data_result['vol']),
                "grossWeight": str(data_result['gross_weight']),
                "netWeight": str(data_result['net_weight']),
                "abc": f"{data_result['abc']}",
                "zjAbc": f"{data_result['zj_abc']}",
                "mfgId": data_result['mfg_id'],
                "mfg": f"{data_result['mfg']}",
                "outFactoryCode": "",
                "model": "",
                "originCountry": f"{data_result['origin_country']}",
                "logistics": "",
                "isBatchManage": data_result['is_batch_manage'],
                "isValidity": data_result['is_validity'],
                "validityType": "",
                "validityDay": 0,
                "warmValidityDay": data_result['warm_validity_day'],
                "isValuables": 0,
                "isCombination": 0,
                "isGift": 0,
                "isConsumables": 0,
                "isChangeable": 0,
                "isProneToMistakes": 0,
                "isHeteromorphicProduct": 0,
                "perQty": data_result['per_qty'],
                "midPackQty": data_result['mid_pack_qty'],
                "isEnable": data_result['is_enable'],
                "auditOpinion": None,
                "auditStatus": None,
                "auditTime": None,
                "auditName": None,
                "barcodeTwo": "",
                "barcodeThree": "",
                "taxCode": "",
                "taxName": "",
                "taxFee": None,
                "tempControl": f"{data_result['temp_control']}",
                "scatteredProperties": "",
                "gmpCertNo": "",
                "approvalNumber": f"{data_result['approval_number']}",
                "categoryPrincipal": "",
                "permitHolder": "",
                "qtyStandard": "",
                "mnemonicCode": f"{data_result['mnemonic_code']}",
                "limitSaleDay": data_result['limit_sale_day'],
                "routeOfAdministration": "",
                "tempMax": None,
                "tempMin": None,
                "minInvoicingUnit": None,
                "optimistic": 0,
                "packFactoryId": 0,
                "productFormType": "YP",
                "isLimitMidPack": 0,
                "hasAnaleptic": 0,
                "tempCondition": None,
                "diCode": None,
                "erpUpdaterName": None,
                "erpUpdateTime": None,
                "erpCreatorName": None,
                "erpCreateTime": None,
                "creditType": None,
                "medicalInsuranceCode": None,
                "instrumentModel": None,
                "entrustMfgId": None,
                "hasAnalepticName": "否",
                "ephedrineName": "是",
                "isDoubleCheckName": "否",
                "isDoubleCheck": 0,
                "isFirstCamp": 0,
                "isFirstCampName": "否",
                "isLimitMidPackName": "否",
                "prodLicenseCode": None,
                "ownerCode": "ZHQCHZ",
                "ownerName": "智汇奇策科技有限公司",
                "skuCategoryName": "药品",
                "skuCategoryCode": None,
                "skuCategoryParentId": None,
                "productFormTypeName": "药品",
                "maintenanceType": "PT",
                "maintenanceTypeName": "一般养护",
                "skuCategorySecondId": None,
                "drugForm": "_",
                "drugFormSpec": "",
                "grmpCertificateNo": None,
                "grmpExpirationDate": "2033-07-31",
                "pzwhExpirationDate": None,
                "bomVOList": None,
                "consumablesVOList": None,
                "certificateVOList": None,
                "approvalNumberList": None,
                "gspData": None,
                "imageVOList": None,
                "packingVOList": None,
                "tempControlName": "常温",
                "isEnableName": "是",
                "scatteredPropertiesName": None,
                "packFactoryName": "",
                "entrustMfgName": "",
                "isValidityName": "否",
                "sumUsableQty": None,
                "auditStatusName": None,
                "isDrugSuperCode": 0,
                "isDrugSuperCodeName": "否",
                "auditorTime": None,
                "outOrderQty": num,
                "priceIncludingTax": 1,
                "productionBatch": f"{orderNo}",
                "stockStatus": "HG",
                "productDate": "2024-01",
                "invalidDate": "2024-12",
                "limitValid": 0,
                "_X_ROW_KEY": "row_243"
            }
        ]
    }
    return data


def yh_data_list(dt_list):
    yh_data_old = {"ownerName": None,
                   "barcode": f"{dt_list['baseSku']['barcode']}",
                   "skuName": f"{dt_list['baseSku']['skuName']}",
                   "skuCategoryId": None,
                   "skuCategoryName": f"{dt_list['baseSku']['skuCategoryName']}",
                   "skuCategoryCode": None,
                   "skuBigCategoryCode": None,
                   "skuBigCategoryName": None,
                   "spec": f"{dt_list['baseSku']['spec']}",
                   "mainUnit": f"{dt_list['baseSku']['mainUnit']}",
                   "perQty": dt_list['baseSku']['perQty'],
                   "originCountry": "",
                   "drugForm": "_",
                   "tradeName": f"{dt_list['baseSku']['tradeName']}",
                   "approvalNumber": f"{dt_list['baseSku']['approvalNumber']}",
                   "brandName": "",
                   "mfgName": None,
                   "mfg": None,
                   "permitHolder": "",
                   "tempControl": "CW",
                   "validityDay": 0,
                   "tempControlName": "常温",
                   "tempMax": None,
                   "tempMin": None,
                   "mnemonicCode": None,
                   "instrumentModel": None,
                   "productionBatch": f"{dt_list['baseInvBatch']['productionBatch']}",
                   "productionDate": f"{dt_list['baseInvBatch']['productionDate']}",
                   "instoreDate": f"{dt_list['baseInvBatch']['instoreDate']}",
                   "invalidDate": f"{dt_list['baseInvBatch']['invalidDate']}",
                   "sterileInvaliDate": "",
                   "sterileNo": "",
                   "asnNo": None,
                   "batchAsnNo": None,
                   "po": None,
                   "unitPrice": None,
                   "spellBoxSign": None,
                   "volume": None,
                   "weight": None,
                   "packQty": None,
                   "_X_ROW_KEY": "row_223"}
    yh_data = {**dt_list, **yh_data_old}
    data = {
        "isEnable": "1",
        "emphMaintainType": "ZD",
        "maintainUser": "lhb001",
        "maintainUserName": "李鸿宾",
        "ownerId": "1770570116141568",
        "flag": 1,
        "orgId": None,
        "productFormType": "YP",
        "productCategory": None,
        "skuCategoryId": None,
        "zoneId": None,
        "lotId": None,
        "skuId": None,
        "delDtIds": [],
        "dtList": [
            yh_data
        ]
    }
    return data


def fj_data(dt_list):
    fj_data_old = {"skuId": dt_list['skuPo']['skuId'],
                   "skuCode": f"{dt_list['skuPo']['skuCode']}",
                   "barcode": f"{dt_list['skuPo']['barcode']}",
                   "skuName": f"{dt_list['skuPo']['skuName']}",
                   "skuCategoryId": None,
                   "skuCategoryName": f"{dt_list['skuPo']['skuCategoryName']}",
                   "skuCategoryCode": f"{dt_list['skuPo']['skuCategoryCode']}",
                   "skuBigCategoryCode": f"{dt_list['skuPo']['skuBigCategoryCode']}",
                   "skuBigCategoryName": f"{dt_list['skuPo']['skuBigCategoryName']}",
                   "spec": f"{dt_list['skuPo']['spec']}",
                   "mainUnit": f"{dt_list['skuPo']['mainUnit']}",
                   "originCountry": "",
                   "drugForm": "_",
                   "tradeName": f"{dt_list['skuPo']['tradeName']}",
                   "approvalNumber": f"{dt_list['skuPo']['approvalNumber']}",
                   "brandName": "",
                   "mfgName": None,
                   "mfg": None,
                   "permitHolder": "",
                   "tempControl": f"{dt_list['skuPo']['tempControl']}",
                   "validityDay": None,
                   "tempControlName": f"{dt_list['skuPo']['tempControlName']}",
                   "tempMax": None,
                   "tempMin": None,
                   "instrumentModel": None,
                   "batchNo": f"{dt_list['baseInvBatch']['batchNo']}",
                   "productionBatch": f"{dt_list['baseInvBatch']['productionBatch']}",
                   "productionDate": f"{dt_list['baseInvBatch']['productionDate']}",
                   "instoreDate": f"{dt_list['baseInvBatch']['instoreDate']}",
                   "invalidDate": f"{dt_list['baseInvBatch']['invalidDate']}",
                   "sterileInvaliDate": "",
                   "sterileNo": "",
                   "batchAsnNo": f"{dt_list['baseInvBatch']['batchAsnNo']}",
                   "po": None,
                   "unitPrice": 1,
                   "spellBoxSign": "",
                   "volume": dt_list['baseInvBatch']['volume'],
                   "weight": dt_list['baseInvBatch']['weight'],
                   "packQty": None,
                   "stockInfoId": f"{dt_list['key']}",
                   "stockId": f"{dt_list['key']}",
                   "_X_ROW_KEY": "row_122",
                   "recheckQty": f"{dt_list['usableQty']}",
                   "recheckReason": "GXQ"}
    fj_data_list = {**dt_list, **fj_data_old}
    data = {
        "isEnable": "1",
        "ownerId": "1770570116141568",
        "flag": 1,
        "productFormType": "YP",
        "productCategory": None,
        "skuCategoryId": None,
        "zoneId": None,
        "lotId": None,
        "skuId": None,
        "delDtIds": [],
        "dtList": [
            fj_data_list
        ]
    }
    return data


def get_bhg_data(dt_list):
    bhg_data_old = {"key": 0.09378168339343351,
                    "approvalNumber": f"{dt_list['approveNo']}",
                    "originZoneName": f"{dt_list['zoneName']}",
                    "originLotName": f"{dt_list['lotCode']}",
                    "packFactoryName": None,
                    "stockId": dt_list['stockInfoId'],
                    "_X_ROW_KEY": "row_132",
                    "badQty": f"{dt_list['usableQty']}",
                    "compensationAmount": 1,
                    "badReason": "GXQ",
                    "dealMsg": "XH"}
    bhg_data_list = {**dt_list, **bhg_data_old}
    data = {
        "isEnable": "1",
        "emphMaintainType": "PT",
        "maintainUser": "lhb001",
        "maintainUserName": "李鸿宾",
        "orgId": None,
        "ownerId": "1770570116141568",
        "flag": 1,
        "productFormType": "YP",
        "isLogisticsCompensation": "N",
        "isShowFlag": False,
        "skuId": None,
        "zoneId": None,
        "lotId": None,
        "productionBatch": None,
        "deleteDtIds": [],
        "dtList": [
            bhg_data_list
        ]
    }
    return data
